---
stages:
  - build
  - test
  - upload

.build:
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --build
  artifacts:
    expire_in: 2 days
    paths:
      - '*.build.json'
      - '*.info'
    reports:
      junit: '*.build.junit.xml'
  except:
    - schedules

.test virtualbox:
  stage: test
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --test-virtualbox
  except:
    - schedules

.test libvirt:
  stage: test
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --test-libvirt

.upload virtualbox:
  stage: upload
  tags:
  - grid5000-shell
  only:
    refs:
      - master
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-virtualbox


.upload libvirt:
  stage: upload
  tags:
  - grid5000-shell
  only:
    refs:
      - master
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-libvirt

.upload-sandbox virtualbox:
  stage: upload
  tags:
  - grid5000-shell
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-sandbox-virtualbox


.upload-sandbox libvirt:
  stage: upload
  tags:
  - grid5000-shell
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-sandbox-libvirt

.regtest:
  stage: build
  tags:
  - grid5000-shell

# ensure that vagrant+virtualbox works with the kernel from bpo
regtest-bpo:
  extends: .regtest
  script:
  - /srv/ci-runner-scripts/bin/test-debian-vagrant-image-bullseye-bpo

regtest-libvirt:
  extends: .regtest
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --regtest-libvirt

regtest-virtualbox:
  extends: .regtest
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --regtest-virtualbox

buster-vagrant-amd64 build:
  extends: .build

buster-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["buster-vagrant-amd64 build"]

buster-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["buster-vagrant-amd64 test-libvirt"]
  when: manual

buster-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["buster-vagrant-amd64 test-libvirt"]
  when: manual

buster-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["buster-vagrant-amd64 build"]

buster-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["buster-vagrant-amd64 test-virtualbox"]
  when: manual

buster-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["buster-vagrant-amd64 test-virtualbox"]
  when: manual

bullseye-vagrant-amd64 build:
  extends: .build

bullseye-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["bullseye-vagrant-amd64 build"]

bullseye-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["bullseye-vagrant-amd64 test-libvirt"]
  when: manual

bullseye-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["bullseye-vagrant-amd64 test-libvirt"]
  when: manual

bullseye-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["bullseye-vagrant-amd64 build"]

bullseye-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["bullseye-vagrant-amd64 test-virtualbox"]
  when: manual

bullseye-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["bullseye-vagrant-amd64 test-virtualbox"]
  when: manual

testing-vagrant-amd64 build:
  extends: .build

testing-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["testing-vagrant-amd64 build"]

testing-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["testing-vagrant-amd64 test-libvirt"]
  when: manual

testing-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["testing-vagrant-amd64 test-libvirt"]
  when: manual

testing-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["testing-vagrant-amd64 build"]

testing-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["testing-vagrant-amd64 test-virtualbox"]
  when: manual

testing-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["testing-vagrant-amd64 test-virtualbox"]
  when: manual

