name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: docker build -t builder .
    - run: docker run --tty --volume $PWD:/mnt --workdir=/mnt --privileged --env VAGRANT_CLOUD_TOKEN builder
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_PAT }}
