name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        sudo make install-build-deps
        sudo apt-get-y install libxml-writer-perl libguestfs-perl uuid-runtime
        make build-libvirt-testing-vagrant-amd64
        make NAMESPACE=fwilhe IS_RELEASE=norelease upload-libvirt-testing-vagrant-amd64
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_PAT }}
